### ISSUE TITLE
Documentation URL not found

### ISSUE THREAD

**Issue by y3nr1ng** [tlambert03/llspy-slm#1]
Nice work! But more documentation would be awesome :p 
[ReadTheDocs](http://llspy.readthedocs.io/en/latest/slm.html) shows me "This page does not exist yet." which is kind of frustrating.

**Comment by tlambert03** [comment]
sorry, link is correct at the top of the page,  will update in the readme
http://llspy-slm.readthedocs.io/en/latest/

**Comment by y3nr1ng** [comment]
Wow, thanks for the quick update!
