### ISSUE TITLE
README.rst activation of environment

### ISSUE THREAD

**Issue by dmilkie** [tlambert03/llspy-slm#2]
In the install [notes](https://github.com/tlambert03/llspy-slm#installation), I think you need "conda" before "activate slmenv".

> conda create -n slmenv
> **conda** activate slmenv

**Comment by tlambert03** [comment]
that's a windows/linux/mac thing... on windows, you just type "activate envname", on linux/mac you type "source activate envname"

https://conda.io/docs/user-guide/tasks/manage-environments.html

let me know if you find otherwise...

**Comment by y3nr1ng** [comment]
In 4.4.0 [release note](https://github.com/conda/conda/blob/master/CHANGELOG.md#new-feature-highlights-1), 
> `conda activate` and `conda deactivate` are now the preferred commands for activating and deactivating environments

:)

**Comment by tlambert03** [comment]
oh fantastic!  I'll update the readme.  thanks for the update!
