### ISSUE TITLE
magnification not correct in batch pattern generation

### ISSUE THREAD

**Issue by Ducros** [tlambert03/llspy-slm#3]
Hello,
When I use the batch pattern generator in the "batch square" tab the magnification seems to be wrong. The pattern created does not fit in the appropriate mask in the lattice light sheet setup. So instead I used the "Generate" tab to create patterns for each wavelengths, Inner NA, Outer NA values. Not a big problem but I wanted to let you know.
Thanks,
Mathieu

**Comment by tlambert03** [comment]
thanks for letting me know.  [v0.2.0](https://github.com/tlambert03/llspy-slm/releases/tag/0.2.0) should now use the magnification that you have set in the main window when doing batch generation.

just an additional note for v0.2.0.  If you install it in a new/clean environment, you will now also need to install either `pyqt` or `pyside2` as an additional dependency.

**Comment by Ducros** [comment]
Thanks.
I actually used the version that is included in llspy. To be sure to use
the latest slm petterngenerator I'll install llspy-slm v0.2.0 in a new
environment and check I have pyqt.
Thanks again for all this work !
Mathieu


Le sam. 26 oct. 2019 à 22:07, Talley Lambert <notifications@github.com> a
écrit :

**Comment by tlambert03** [comment]
no problem,
it should be fine to just update it in the llspy environment too if you want.   in your llspy environment, run:
`conda update llspy-slm`
or
`conda install llspy-slm=0.2.0`

and note that you can always launch the slm pattern generator independently of llspy by running "`slmgen`" at the command prompt

feel free to reopen this if you run into more issues.
